// <auto-generated />
using System;
using GardenHelperApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenHelperApp.Server.Migrations
{
    [DbContext(typeof(GardenContext))]
    partial class GardenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GardenHelperApp.Shared.Models.GardenModel", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardinessZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeatZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarineInfluence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilType")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindOrientation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("GardenId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.JournalEntryModel", b =>
                {
                    b.Property<int>("JournalEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entry")
                        .HasColumnType("TEXT");

                    b.Property<int>("GardenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JournalEntryId");

                    b.HasIndex("GardenId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.LocationModel", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DistancetoLight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GardenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Humidity")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsOutside")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lighting")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemperatureConsistency")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowFacing")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.HasIndex("GardenId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.ObservationModel", b =>
                {
                    b.Property<int>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveObservation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObservationId");

                    b.HasIndex("PlantId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.PlantInformationModel", b =>
                {
                    b.Property<int>("PlantInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Air")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Container")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fertilization")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrowingSeason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .HasColumnType("TEXT");

                    b.Property<string>("Light")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoMimeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Propagation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pruning")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seeds")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Water")
                        .HasColumnType("TEXT");

                    b.HasKey("PlantInformationId");

                    b.ToTable("PlantInformation");
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.PlantModel", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("GardenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantInformationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlantId");

                    b.HasIndex("GardenId");

                    b.HasIndex("LocationId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.PlantPhotoModel", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoMimeType")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId");

                    b.ToTable("PlantPhotos");
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultGardenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.JournalEntryModel", b =>
                {
                    b.HasOne("GardenHelperApp.Shared.Models.GardenModel", null)
                        .WithMany()
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.LocationModel", b =>
                {
                    b.HasOne("GardenHelperApp.Shared.Models.GardenModel", null)
                        .WithMany()
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.ObservationModel", b =>
                {
                    b.HasOne("GardenHelperApp.Shared.Models.PlantModel", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GardenHelperApp.Shared.Models.PlantModel", b =>
                {
                    b.HasOne("GardenHelperApp.Shared.Models.GardenModel", null)
                        .WithMany()
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenHelperApp.Shared.Models.LocationModel", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
